### ISSUE TITLE
Refactor Logging Scope

### ISSUE THREAD

**Issue by digitalextremist** [abstractive/celluloid#3]
Project for @dilumnavanjana to become oriented to `Celluloid` before [GSoC](http://www.google-melange.com/gsoc/proposal/review/org/google/gsoc2015/dilumnavanjana/5750085036015616)
Focuses on resolving celluloid/celluloid#420
Handled in the ongoing #2 pull request.

**Comment by digitalextremist** [comment]
Per the scope of the issue, we move all "non-public" classes into `Celluloid::Internals` ...

So which Classes are "non-public" first of all, @dilumnavanjana?

**Comment by dilumnavanjana** [comment]
```logger``` & ```Handler``` are mentioned in the issue, To find out other non-public classes I have to add them in to Internals one by one & check.

**Comment by digitalextremist** [comment]
Sounds good @dilumn ( see what I did there @dilumnavanjana )

**Comment by dilumnavanjana** [comment]
Committed new changes to my forked project, but it seems before adding them to the master branch, I should test them badly. Do you think rspec is enough @digitalextremist ??

**Comment by digitalextremist** [comment]
This is an important thing to pay attention to. I used to make that mistake a lot ( pushing to the wrong branch ) so I used this:

Add this to your `.profile`:
```
source ~/.git-prompt.sh #de see link below
export PS1='\[\033[01;34m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[01;34m\] \w\[\033[31m\]$(__git_ps1 " >> %s") \[\033[01;34m\]$\[\033[00m\] '
```

Then use this Mac OS X fix:

* http://stackoverflow.com/a/12871094/1169705

**Comment by dilumnavanjana** [comment]
Configured `.profile` as mentioned above, by the way I pushed to the write branch isn't it? @digitalextremist

**Comment by dilumnavanjana** [comment]
Adding all non public classes to a new directory causes a big change Celluloid, because path change, for example `require 'celluloid/internal/fiber'`. We have to change all the paths & also after releasing this version, old projects have to modify the path. What do you think about this @digitalextremist ??

**Comment by digitalextremist** [comment]
We are bypassing `0.16.5` and going right to `0.17.0` so a very large breaking change is fine.

**Comment by dilumnavanjana** [comment]
Here is the list I found so far,

```ruby
require 'celluloid/internal/core_ext'
require 'celluloid/internal/cpu_counter'
require 'celluloid/internal/fiber'
require 'celluloid/internal/fsm'
require 'celluloid/internal/internal_pool'
require 'celluloid/internal/links'
require 'celluloid/internal/logger'
require 'celluloid/internal/evented_mailbox'
require 'celluloid/internal/method'
require 'celluloid/internal/handlers'
require 'celluloid/internal/receivers'
require 'celluloid/internal/registry'
require 'celluloid/internal/responses'
require 'celluloid/internal/signals'
require 'celluloid/internal/stack_dump'
require 'celluloid/internal/system_events'
require 'celluloid/internal/tasks'
require 'celluloid/internal/task_set'
require 'celluloid/internal/thread_handle'
require 'celluloid/internal/uuid

**Comment by digitalextremist** [comment]
I need to pause on this so I can give you my full attention. I will give you new instructions in IRC.

**Comment by digitalextremist** [comment]
I've taken this over.
